id: I67230642
legacy_id: P004473
ocr_import_info:
  bdrc_scan_id: W2123
  source: bdrc
  ocr_info:
    timestamp: '2021-01-18T11:23:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T13:59:41.855695+00:00'
last_modified: 2022-09-01 21:59:47.155426
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2123
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2123
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགག་ལན་ནོར་བུ་ཀེ་ཏ་ཀའི་བྱི་དོར།
  author: ཐུའུ་བཀྭན ༠༣་བློ་བཟང་ཆོས་ཀྱི་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.7266147500615612
  ocr_word_median_confidence_index: 0.8
quality: null
bases:
  I5403:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5403
      total_pages: 74
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5403.txt
    statistics:
      ocr_word_median_confidence_index: 0.8
      ocr_word_mean_confidence_index: 0.7266147500615612
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
