id: I67230642
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:54:10+00:00'
last_modified: '2022-06-08T01:20:11.499671+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2123
  title: དགག་ལན་ནོར་བུ་ཀེ་ཏ་ཀའི་བྱི་དོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9DAA:
      image_group_id: I5403
      title: ''
      total_pages: 74
      order: 1
      base_file: 9DAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
